version: "3"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - GOOGLE_API_CLIENT_ID=${GOOGLE_API_CLIENT_ID}
      - GOOGLE_API_CLIENT_SECRET=${GOOGLE_API_CLIENT_SECRET}
      - GOOGLE_API_MEIBO_SHEET_URI=${GOOGLE_API_MEIBO_SHEET_URI}
      - SESSION_SECRET=${SESSION_SECRET}
      - GOOGLE_API_REDIRECT_URI=${GOOGLE_API_REDIRECT_URI}
      - BASE_URL=${BASE_URL}
      - LOG_LEVEL=${LOG_LEVEL}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PRISMA_URL=${POSTGRES_PRISMA_URL}
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_URL_NON_POOLING=${POSTGRES_URL_NON_POOLING}
      - POSTGRES_USER=${POSTGRES_USER}
      - VERCEL_WEB_ANALYTICS_ID=${VERCEL_WEB_ANALYTICS_ID}
